version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/bundle
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
    ports:
      - 3000:3000
    links:
      - pg
    command: bash -c "rm tmp/pids/server.pid ; bundle exec rails server -b 0.0.0.0"
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  node_modules: {}
  bundle_cache: {}
  pg-data: {}
