version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/bundle
      - node_modules:/app/node_modules
    environment:
      - PORT=3000
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
    links:
      - pg
      - redis
    command: bash -c "rm tmp/pids/server.pid ; bundle exec rails server -b 0.0.0.0"
  worker:
    build: .
    volumes:
      - .:/app
      - bundle_cache:/bundle
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
    links:
      - pg
      - redis
    command: bundle exec sidekiq
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  node_modules: {}
  bundle_cache: {}
  pg-data: {}
  redis-data: {}
